server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${app.mail.from}
    password: root
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  application:
    name: exchange-api
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
          apilayerApiClient:
            url: ${external.exchange-api.base-url}
            default-request-headers:
              apikey: ${external.exchange-api.access-key}

external:
  exchange-api:
    base-url: https://api.exchangeratesapi.io/v1
    access-key: cb9bf701e9fda89cafcf6a5641c9f4ed

app:
  security:
    user: user
    password: user
  mail:
    from: patrykszmcz459@gmail.com
    to: patryk.szymanczyk1@gmail.com